name: Build Caddy All

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_caddy_all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.25
      - run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive --with github.com/caddy-dns/cloudflare --output caddy-nc-v2
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v3 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive --with github.com/caddy-dns/cloudflare --output caddy-nc-v3

          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/zedifen/forwardproxy@naive --with github.com/caddy-dns/cloudflare --output caddy-zed-nc-v2
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v3 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/zedifen/forwardproxy@naive --with github.com/caddy-dns/cloudflare --output caddy-zed-nc-v3

          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/aUsernameWoW/forwardproxy@udpintcp --with github.com/caddy-dns/cloudflare --output caddy-wow-nc-v2
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v3 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/aUsernameWoW/forwardproxy@udpintcp --with github.com/caddy-dns/cloudflare --output caddy-wow-nc-v3

          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive --with github.com/caddy-dns/cloudflare --with github.com/mholt/caddy-l4 --output caddy-ncl-v2
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v3 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive --with github.com/caddy-dns/cloudflare --with github.com/mholt/caddy-l4 --output caddy-ncl-v3

          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/zedifen/forwardproxy@naive --with github.com/caddy-dns/cloudflare --with github.com/mholt/caddy-l4 --output caddy-zed-ncl-v2
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v3 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/zedifen/forwardproxy@naive --with github.com/caddy-dns/cloudflare --with github.com/mholt/caddy-l4 --output caddy-zed-ncl-v3

          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/aUsernameWoW/forwardproxy@udpintcp --with github.com/caddy-dns/cloudflare --with github.com/mholt/caddy-l4 --output caddy-wow-ncl-v2
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v3 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/aUsernameWoW/forwardproxy@udpintcp --with github.com/caddy-dns/cloudflare --with github.com/mholt/caddy-l4 --output caddy-wow-ncl-v3

          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive --with github.com/caddy-dns/cloudflare --with github.com/imgk/caddy-trojan --with github.com/mholt/caddy-l4 --output caddy-nctl-v2
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v3 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive --with github.com/caddy-dns/cloudflare --with github.com/imgk/caddy-trojan --with github.com/mholt/caddy-l4 --output caddy-nctl-v3

          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/zedifen/forwardproxy@naive --with github.com/caddy-dns/cloudflare  --with github.com/imgk/caddy-trojan --with github.com/mholt/caddy-l4 --output caddy-zed-nctl-v2
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v3 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/zedifen/forwardproxy@naive --with github.com/caddy-dns/cloudflare  --with github.com/imgk/caddy-trojan --with github.com/mholt/caddy-l4 --output caddy-zed-nctl-v3

          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/aUsernameWoW/forwardproxy@udpintcp --with github.com/caddy-dns/cloudflare --with github.com/imgk/caddy-trojan --with github.com/mholt/caddy-l4 --output caddy-wow-nctl-v2
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v3 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/aUsernameWoW/forwardproxy@udpintcp --with github.com/caddy-dns/cloudflare --with github.com/imgk/caddy-trojan --with github.com/mholt/caddy-l4 --output caddy-wow-nctl-v3

      - name: Set variables
        run: |
          echo "TAG_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name:  Upload caddy (Linux & Windows)
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: CaddyAll-${{ env.TAG_DATE }}
          name: CaddyAll-${{ env.TAG_DATE }}
          files: |
            caddy-nc-v2
            caddy-nc-v3
            caddy-zed-nc-v2
            caddy-zed-nc-v3
            caddy-wow-nc-v2
            caddy-wow-nc-v3
            caddy-ncl-v2
            caddy-ncl-v3
            caddy-zed-ncl-v2
            caddy-zed-ncl-v3
            caddy-wow-ncl-v2
            caddy-wow-ncl-v3
            caddy-nctl-v2
            caddy-nctl-v3
            caddy-zed-nctl-v2
            caddy-zed-nctl-v3
            caddy-wow-nctl-v2
            caddy-wow-nctl-v3
          preserve_order: true
          draft: false
          prerelease: true
          make_latest: false
